/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base.de.datos.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    Connection myConn = null;
    Statement myStmt = null;

    /**
     * Creates new form Login
     */
    public Login() {
        try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/DB_Taller?useSSL=true", "root", "jordi123");
            myStmt = myConn.createStatement();
            System.out.println("conecta");
        } catch (SQLException e) {
            e.printStackTrace();
        }

        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
        System.out.println("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_administador = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jd_admin_asesores = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_asesores_pnombre = new javax.swing.JTextField();
        txt_asesores_papellido = new javax.swing.JTextField();
        txt_asesores_snombre = new javax.swing.JTextField();
        txt_asesores_sapellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_asesores_numtel = new javax.swing.JTextField();
        btn_asesores_agregar = new javax.swing.JButton();
        btn_asesor_modif = new javax.swing.JButton();
        btn_asesor_eliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_asesor_modif = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cb_asesor_eliminar = new javax.swing.JComboBox<>();
        jd_admin_mecanicos = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        btn_mecanico_agregar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_mecanico_modif = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btn_asesor_eliminar1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_mecanico_pnombre = new javax.swing.JTextField();
        txt_mecanico_papellido = new javax.swing.JTextField();
        cb_asesor_modif1 = new javax.swing.JComboBox<>();
        txt_mecanico_snombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_mecanico_sapellido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cb_mecanico_eliminar = new javax.swing.JComboBox<>();
        txt_mecanico_numtel = new javax.swing.JTextField();
        jd_principal_asesor = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_login_password = new javax.swing.JTextField();
        btn_login_ingresar = new javax.swing.JButton();
        txt_login_user = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        jButton1.setText("ASESORES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("MECANICOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_administadorLayout = new javax.swing.GroupLayout(jd_administador.getContentPane());
        jd_administador.getContentPane().setLayout(jd_administadorLayout);
        jd_administadorLayout.setHorizontalGroup(
            jd_administadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administadorLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jd_administadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jd_administadorLayout.setVerticalGroup(
            jd_administadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_administadorLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jButton4)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jLabel1.setText("ASESORES");

        jLabel6.setText("Primer Nombre:");

        jLabel7.setText("Segundo Nombre:");

        jLabel8.setText("Primer Apellido");

        jLabel9.setText("Segundo Apellido:");

        jLabel10.setText("Numero de Telefono");

        btn_asesores_agregar.setText("Agregar");

        btn_asesor_modif.setText("Modificar");

        btn_asesor_eliminar.setText("Eliminar");

        jLabel11.setText("Modificar Asesor:");

        jLabel12.setText("Agregar Asesor:");

        jLabel13.setText("Eliminar Asesor:");

        javax.swing.GroupLayout jd_admin_asesoresLayout = new javax.swing.GroupLayout(jd_admin_asesores.getContentPane());
        jd_admin_asesores.getContentPane().setLayout(jd_admin_asesoresLayout);
        jd_admin_asesoresLayout.setHorizontalGroup(
            jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_asesores_numtel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(26, 26, 26)
                                        .addComponent(txt_asesores_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_asesores_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(22, 22, 22)
                                            .addComponent(txt_asesores_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_asesores_sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel1)))))
                    .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btn_asesores_agregar)))
                .addGap(63, 63, 63)
                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_asesor_modif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                        .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(btn_asesor_modif)
                            .addComponent(btn_asesor_eliminar)
                            .addComponent(jLabel13))
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addComponent(cb_asesor_eliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_admin_asesoresLayout.setVerticalGroup(
            jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_asesores_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_asesores_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_asesor_modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_asesores_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_asesores_sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_admin_asesoresLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_asesor_modif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_admin_asesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_asesores_numtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_asesor_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_asesores_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_asesor_eliminar)
                .addGap(24, 24, 24))
        );

        jLabel14.setText("MECANICOS");

        btn_mecanico_agregar.setText("Agregar");

        jLabel15.setText("Primer Nombre:");

        btn_mecanico_modif.setText("Modificar");

        jLabel16.setText("Segundo Nombre:");

        btn_asesor_eliminar1.setText("Eliminar");

        jLabel17.setText("Primer Apellido");

        jLabel18.setText("Modificar Mecanico:");

        jLabel19.setText("Segundo Apellido:");

        jLabel20.setText("Agregar Mecanico:");

        jLabel21.setText("Eliminar Mecanico:");

        jLabel22.setText("Numero de Telefono");

        javax.swing.GroupLayout jd_admin_mecanicosLayout = new javax.swing.GroupLayout(jd_admin_mecanicos.getContentPane());
        jd_admin_mecanicos.getContentPane().setLayout(jd_admin_mecanicosLayout);
        jd_admin_mecanicosLayout.setHorizontalGroup(
            jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_mecanico_numtel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(26, 26, 26)
                                        .addComponent(txt_mecanico_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_mecanico_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(22, 22, 22)
                                            .addComponent(txt_mecanico_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_mecanico_sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel14)))))
                    .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btn_mecanico_agregar)))
                .addGap(63, 63, 63)
                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_asesor_modif1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                        .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(btn_mecanico_modif)
                            .addComponent(btn_asesor_eliminar1)
                            .addComponent(jLabel21))
                        .addGap(0, 85, Short.MAX_VALUE))
                    .addComponent(cb_mecanico_eliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_admin_mecanicosLayout.setVerticalGroup(
            jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_mecanico_pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_mecanico_snombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_asesor_modif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_mecanico_papellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_mecanico_sapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_admin_mecanicosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_mecanico_modif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_admin_mecanicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_mecanico_numtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_mecanico_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_mecanico_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_asesor_eliminar1)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jd_principal_asesorLayout = new javax.swing.GroupLayout(jd_principal_asesor.getContentPane());
        jd_principal_asesor.getContentPane().setLayout(jd_principal_asesorLayout);
        jd_principal_asesorLayout.setHorizontalGroup(
            jd_principal_asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_principal_asesorLayout.setVerticalGroup(
            jd_principal_asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel23.setText("jLabel23");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 100, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 188, -1, -1));
        getContentPane().add(txt_login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 120, -1));

        btn_login_ingresar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btn_login_ingresar.setText("INGRESAR");
        btn_login_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 30));
        getContentPane().add(txt_login_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/ColorAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_ingresarActionPerformed
        // TODO add your handling code here:
        System.out.println("Hola");
        String user = txt_login_user.getText();
        String password = txt_login_password.getText();
        if (user.contentEquals("admin") && password.contentEquals("1234")) {
            jd_administador.setModal(true);
            jd_administador.pack();
            jd_administador.setVisible(true);
        }
    }//GEN-LAST:event_btn_login_ingresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jd_admin_asesores.setModal(true);
        jd_admin_asesores.pack();
        jd_admin_asesores.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jd_admin_mecanicos.setModal(true);
        jd_admin_mecanicos.pack();
        jd_admin_mecanicos.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asesor_eliminar;
    private javax.swing.JButton btn_asesor_eliminar1;
    private javax.swing.JButton btn_asesor_modif;
    private javax.swing.JButton btn_asesores_agregar;
    private javax.swing.JButton btn_login_ingresar;
    private javax.swing.JButton btn_mecanico_agregar;
    private javax.swing.JButton btn_mecanico_modif;
    private javax.swing.JComboBox<String> cb_asesor_eliminar;
    private javax.swing.JComboBox<String> cb_asesor_modif;
    private javax.swing.JComboBox<String> cb_asesor_modif1;
    private javax.swing.JComboBox<String> cb_mecanico_eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog jd_admin_asesores;
    private javax.swing.JDialog jd_admin_mecanicos;
    private javax.swing.JDialog jd_administador;
    private javax.swing.JDialog jd_principal_asesor;
    private javax.swing.JTextField txt_asesores_numtel;
    private javax.swing.JTextField txt_asesores_papellido;
    private javax.swing.JTextField txt_asesores_pnombre;
    private javax.swing.JTextField txt_asesores_sapellido;
    private javax.swing.JTextField txt_asesores_snombre;
    private javax.swing.JTextField txt_login_password;
    private javax.swing.JTextField txt_login_user;
    private javax.swing.JTextField txt_mecanico_numtel;
    private javax.swing.JTextField txt_mecanico_papellido;
    private javax.swing.JTextField txt_mecanico_pnombre;
    private javax.swing.JTextField txt_mecanico_sapellido;
    private javax.swing.JTextField txt_mecanico_snombre;
    // End of variables declaration//GEN-END:variables
}
